language: ruby
jobs:
  include:
    - rvm: 2.7
      dist: focal
    - rvm: 2.6
      dist: bionic
    - rvm: 2.5
      dist: bionic
cache:
  bundler: true
before_script: bundle exec rake compile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
