image: Visual Studio 2019

environment:
  matrix:
    - RUBY_VERSION: "26-x64"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_build:
  - ruby -v
  - gem -v
  - bundle -v
  - pwd

build_script:
  - curl -fSL -o or-tools.zip https://github.com/google/or-tools/releases/download/v7.6/or-tools_VisualStudio2019-64bit_v7.6.7691.zip
  - unzip or-tools.zip
  - ridk enable
  - bundle exec rake compile -- --with-or-tools-dir=C:\projects\or-tools\or-tools_VisualStudio2019-64bit_v7.6.7691

test_script:
  - bundle exec rake test
